import { groupPaths, logoViewBox, markParts, markViewBox, wordPaths } from "@/lib/logo";

/* Eric Wright Group logo from its own vector parts (lib/logo.ts, generated by scripts/logo.py).
   The EW mark and "Group" stay orange on every ground; "Eric Wright" takes `currentColor`, so it follows the
   header tone (white over the film, black on light sections), exactly as the live header swaps logo files.
   `parts` tags every shape with data-part so the preloader can build it piece by piece. */
export function Logo({ title = "Eric Wright Group", markOnly = false, parts = false, className = "" }: { title?: string; markOnly?: boolean; parts?: boolean; className?: string }) {
  return <svg className={`logo ${className}`} viewBox={markOnly ? markViewBox : logoViewBox} role={title ? "img" : undefined} aria-label={title || undefined} aria-hidden={title ? undefined : true} focusable="false">
    <g className="logo-mark" fill="var(--orange)">
      {markParts.map((p) => <path key={p.id} d={p.d} data-part={parts ? p.id : undefined} />)}
    </g>
    {!markOnly && <>
      <g className="logo-word" fill="currentColor" data-part={parts ? "word" : undefined}>{wordPaths.map((d, i) => <path key={i} d={d} />)}</g>
      <g className="logo-group" fill="var(--orange)" data-part={parts ? "group" : undefined}>{groupPaths.map((d, i) => <path key={i} d={d} />)}</g>
    </>}
  </svg>;
}
