"""Splits the live header logo into named parts for components/Logo.tsx and the preloader.

Source: /images/eric-wright/header/transparent-logo.svg (downloaded by `npm run media` into _scrape/brand/).
It is a true vector lock-up, 180 x 129, made of 26 filled paths in three groups:
  - the EW mark (6 orange shapes, y 0 to 48): three horizontal bars that read as the E, and three slanted strokes
    that read as the W (a solid left wedge, a middle stroke whose foot meets the bottom bar, and a free right stroke)
  - "Eric Wright" (15 white shapes, y 61 to 88): letters plus the counters and dots cut as separate shapes
  - "Group" (5 orange shapes, y 102 to 129)
Paths are classified by their position in the file, which matches that order; the script checks each bounding box
so a change on the live site fails loudly instead of mislabelling a part.
Run: npm run logo
"""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
svg = (ROOT / "_scrape/brand/transparent-logo.svg").read_text()
paths = re.findall(r'<path d="([^"]+)"(?: fill="([^"]+)")?', svg)
assert len(paths) == 26, f"expected 26 paths, found {len(paths)}"


def bbox(d):
    # Absolute M/L/H/V/C/Z only (asserted); control points are included, which is close enough to classify.
    assert not re.search(r"[a-y]", d), "relative path commands"
    xs, ys, x, y = [], [], 0.0, 0.0
    for cmd, args in re.findall(r"([MLHVCZ])([^MLHVCZ]*)", d):
        nums = [float(n) for n in re.findall(r"-?\d*\.?\d+", args)]
        if cmd == "H":
            for x in nums: xs.append(x); ys.append(y)
        elif cmd == "V":
            for y in nums: xs.append(x); ys.append(y)
        elif cmd in "MLC":
            for i in range(0, len(nums), 2):
                x, y = nums[i], nums[i + 1]; xs.append(x); ys.append(y)
    return min(xs), min(ys), max(xs), max(ys)


word = [d for d, fill in paths[0:15]]
group = [d for d, fill in paths[15:20]]
mark = {
    "bar-top": paths[20][0],
    "bar-bottom": paths[21][0],
    "w-left": paths[22][0],
    "w-mid": paths[23][0],
    "bar-mid": paths[24][0],
    "w-right": paths[25][0],
}
assert all(fill == "white" for _, fill in paths[0:15])
assert all(fill == "#F26400" for _, fill in paths[15:26])
assert all(bbox(d)[3] < 49 for d in mark.values()), "mark sits above y 48"
assert all(bbox(d)[3] > 100 for d in group), "Group sits below y 100"

# Build order for the preloader: the E's bars top to bottom, then the W's strokes left to right.
order = ["bar-top", "bar-mid", "bar-bottom", "w-left", "w-mid", "w-right"]

out = f"""// Generated by scripts/logo.py from the live header logo (transparent-logo.svg). Do not edit by hand.
// 26 vector shapes: the EW mark (6), "Eric Wright" (15) and "Group" (5).

export const logoViewBox = "0 0 180 129";
// The mark alone, as the live sticky header shows it (sticky-logo.svg is the same six shapes).
export const markViewBox = "0 0 105.4 48";

export type MarkPart = {{ id: string; d: string }};
export const markParts: MarkPart[] = {json.dumps([{"id": k, "d": mark[k]} for k in order], indent=2)};

export const wordPaths: string[] = {json.dumps(word, indent=2)};

export const groupPaths: string[] = {json.dumps(group, indent=2)};
"""
(ROOT / "lib/logo.ts").write_text(out)

# Favicon: the mark, orange on black, square tile.
fav = "".join(f'<path d="{mark[k]}"/>' for k in order)
(ROOT / "app/icon.svg").write_text(
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="-12 -40.6 129.4 129.4">'
    '<rect x="-12" y="-40.6" width="129.4" height="129.4" rx="14" fill="#000"/>'
    f'<g fill="#F26400">{fav}</g></svg>\n'
)
print("lib/logo.ts:", len(order), "mark parts,", len(word), "word shapes,", len(group), "group shapes; app/icon.svg")
